clear; clc; close all;

fn = '../EnergyData/COMBINED_VARIABLES_SOLAR.MAT';
%fn = '../EnergyData/COMBINED_VARIABLES_PIEZO.MAT';
%fn = '../EnergyData/COMBINED_VARIABLES_SOLARPIEZO.MAT';

load(fn);

histbins = 200;

figure(1)
subplot(4,1,1)
plot(scaledtime_roof2/3600, powersolar_roof2, '.')
ylabel('Power (Watts)')
xlabel('Time (Hours)')
title('Solar Roof2')
subplot(4,1,2)
plot(scaledtime_roof/3600, powersolar_roof, '.')
ylabel('Power (Watts)')
xlabel('Time (Hours)')
title('Solar Roof')
subplot(4,1,3)
plot(scaledtime_door/3600, powersolar_door, '.')
ylabel('Power (Watts)')
xlabel('Time (Hours)')
title('Solar Office Door')
subplot(4,1,4)
plot(scaledtime_car/3600, powersolar_car, '.')
ylabel('Power (Watts)')
xlabel('Time (Hours)')
title('Solar Car Boot')

figure(2)
subplot(4,1,1)
plot(scaledtime_roof2/3600, trimmedlight_roof2, '.')
ylabel('Brightness (Lux)')
xlabel('Time (Hours)')
title('Lux Roof2')
subplot(4,1,2)
plot(scaledtime_roof/3600, trimmedlight_roof, '.')
ylabel('Brightness (Lux)')
xlabel('Time (Hours)')
title('Lux Roof')
subplot(4,1,3)
plot(scaledtime_door/3600, trimmedlight_door, '.')
ylabel('Brightness (Lux)')
xlabel('Time (Hours)')
title('Lux Office Door')
subplot(4,1,4)
plot(scaledtime_car/3600, trimmedlight_car, '.')
ylabel('Brightness (Lux)')
xlabel('Time (Hours)')
title('Lux Car Boot')

figure(3)
subplot(4,1,1)
hist(powersolar_roof2, histbins)
ylabel('Frequency')
xlabel('Energy (Watt)')
title('Solar Histogram Roof2')
subplot(4,1,2)
hist(powersolar_roof, histbins)
ylabel('Frequency')
xlabel('Energy (Watt)')
title('Solar Histogram Roof')
subplot(4,1,3)
hist(powersolar_door, histbins)
ylabel('Frequency')
xlabel('Energy (Watt)')
title('Solar Histogram Office Door')
subplot(4,1,4)
hist(powersolar_car, histbins)
ylabel('Frequency')
xlabel('Energy (Watt)')
title('Solar Histogram Car Boot')

figure(4)
subplot(4,1,1)
hist(powerpiezo_roof2, histbins)
ylabel('Frequency')
xlabel('Energy (Watt)')
title('Piezo Histogram Roof2')
subplot(4,1,2)
hist(powerpiezo_roof, histbins)
ylabel('Frequency')
xlabel('Energy (Watt)')
title('Piezo Histogram Roof')
subplot(4,1,3)
hist(powerpiezo_door, histbins)
ylabel('Frequency')
xlabel('Energy (Watt)')
title('Piezo Histogram Office Door')
subplot(4,1,4)
hist(powerpiezo_car, histbins)
ylabel('Frequency')
xlabel('Energy (Watt)')
title('Piezo Histogram Car Boot')
